# Generated by Django 4.0.5 on 2022-07-14 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_is_on_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='is_on_wishlist',
        ),
    ]
